---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: hpa-demo  
spec:
  scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: nginx          
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 50  


