---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
        name: test-netpol
        namespace: casestudy-ns
spec:
  podSelector:
    matchLabels:
      app: MyTestApp
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.8/8
   

